import { AlertBanner, Badge, Card, DashboardMetricCard, DataTable, StatusBadge, Timeline } from "@safebus/ui";
import { alerts, buses, drivers, routeStops, routes, scanEvents, students, trips } from "../../data/mockData";
import { MapPlaceholder } from "../../components/MapPlaceholder";
import type { Trip } from "@safebus/types";
const metrics = [["Active Trips",2,"Across tenant routes"],["Delayed Buses",1,"Needs dispatch review"],["GPS Lost",1,"Verify by radio"],["Students Picked Up",128,"Mock aggregate"],["Students Dropped Off",0,"Morning routes active"],["Manual Overrides",3,"Review after route"]] as const;
export function AdminHome() { return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-3">{metrics.map((m) => <DashboardMetricCard key={m[0]} label={m[0]} value={m[1]} helper={m[2]} tone={m[0].includes("GPS") ? "red" : "navy"} />)}</div><div className="grid gap-4 xl:grid-cols-3"><div className="xl:col-span-2"><MapPlaceholder /></div><Card><h3 className="text-xl font-black">Alerts</h3><div className="mt-4 space-y-3">{alerts.map((a) => <AlertBanner key={a.id} title={a.type} message={a.message} tone={a.urgency === "critical" ? "red" : "amber"} />)}</div></Card></div><TripsTable /><Timeline items={scanEvents.map((e) => ({ time: e.occurredAt, title: e.eventType.replace("_", " "), detail: "Privacy-safe student event recorded" }))} /></div>; }
export function LiveMapPage() { return <MapPlaceholder />; }
export function TripsTable() { const columns = [{ key: "trip", header: "Trip", render: (t: Trip) => t.id }, { key: "route", header: "Route", render: () => routes[0].name }, { key: "bus", header: "Bus", render: (t: Trip) => buses.find((b) => b.id === t.busId)?.busNumber }, { key: "driver", header: "Driver", render: (t: Trip) => drivers.find((d) => d.id === t.driverId)?.name }, { key: "status", header: "Status", render: (t: Trip) => <StatusBadge status={t.status} /> }, { key: "start", header: "Start Time", render: (t: Trip) => t.startTime }, { key: "gps", header: "Last GPS Update", render: (t: Trip) => t.lastGpsUpdate ?? "Unavailable" }, { key: "progress", header: "Pickup Progress", render: (t: Trip) => `${t.pickupProgress}%` }, { key: "alerts", header: "Alerts", render: (t: Trip) => t.alertIds.length }]; return <Card><div className="mb-4 flex flex-wrap gap-2">{["Active","Scheduled","Delayed","Completed","GPS Lost","Morning","Afternoon"].map((f) => <Badge key={f} tone="gray">{f}</Badge>)}</div><DataTable columns={columns} rows={trips} /></Card>; }
export function TripsPage() { return <TripsTable />; }
export function PlaceholderPage({ title }: { title: string }) { return <Card><h2 className="text-2xl font-black">{title}</h2><p className="mt-2 text-slate-600">Role-based placeholder using tenant-scoped mock data for Milestone 1.</p><p className="mt-4 text-sm">Routes: {routes.length} · Stops: {routeStops.length} · Students: {students.length}</p></Card>; }
