import { Navigate, Route, Routes } from "react-router-dom";
import { AdminLayout } from "./layouts/AdminLayout";
import { DriverLayout } from "./layouts/DriverLayout";
import { ParentLayout } from "./layouts/ParentLayout";
import { ForgotPassword, Login, ResetPassword } from "./pages/AuthPages";
import { Landing } from "./pages/Landing";
import { AdminHome, LiveMapPage, PlaceholderPage, TripsPage } from "./pages/admin/AdminPages";
import { ActiveTrip, DriverHome, IssuePage, ManualPage, ScanPage, SummaryPage } from "./pages/driver-demo/DriverPages";
import { ParentBus, ParentHome, ParentNotifications, ParentPlaceholder, ParentTimeline } from "./pages/parent/ParentPages";
export function App() { return <Routes><Route path="/" element={<Landing />} /><Route path="/login" element={<Login />} /><Route path="/forgot-password" element={<ForgotPassword />} /><Route path="/reset-password" element={<ResetPassword />} /><Route path="/admin" element={<AdminLayout />}><Route index element={<AdminHome />} /><Route path="live-map" element={<LiveMapPage />} /><Route path="trips" element={<TripsPage />} />{["routes","students","guardians","drivers","buses","imports","reports","settings","audit-logs"].map((p) => <Route key={p} path={p} element={<PlaceholderPage title={p.replace("-", " ")} />} />)}</Route><Route path="/parent" element={<ParentLayout />}><Route index element={<ParentHome />} /><Route path="students" element={<ParentPlaceholder title="Assigned students" />} /><Route path="bus" element={<ParentBus />} /><Route path="timeline" element={<ParentTimeline />} /><Route path="notifications" element={<ParentNotifications />} /><Route path="help" element={<ParentPlaceholder title="Help" />} /></Route><Route path="/driver-demo" element={<DriverLayout />}><Route index element={<DriverHome />} /><Route path="trips" element={<DriverHome />} /><Route path="active-trip" element={<ActiveTrip />} /><Route path="scan" element={<ScanPage />} /><Route path="manual" element={<ManualPage />} /><Route path="report-issue" element={<IssuePage />} /><Route path="summary" element={<SummaryPage />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
