import type { ButtonHTMLAttributes, ReactNode } from "react";
import type { TripStatus } from "@safebus/types";

type Tone = "navy" | "yellow" | "green" | "amber" | "red" | "gray";
const toneClasses: Record<Tone, string> = { navy: "bg-slate-900 text-white", yellow: "bg-yellow-300 text-slate-950", green: "bg-emerald-100 text-emerald-800", amber: "bg-amber-100 text-amber-900", red: "bg-red-100 text-red-800", gray: "bg-slate-100 text-slate-700" };
export function Button({ children, variant = "primary", className = "", ...props }: { children: ReactNode; variant?: "primary" | "secondary" | "ghost"; className?: string } & ButtonHTMLAttributes<HTMLButtonElement>) {
  const variants = { primary: "bg-slate-900 text-white hover:bg-slate-800", secondary: "bg-yellow-300 text-slate-950 hover:bg-yellow-200", ghost: "bg-white text-slate-900 ring-1 ring-slate-200 hover:bg-slate-50" };
  return <button className={`rounded-xl px-4 py-2 font-semibold transition ${variants[variant]} ${className}`} {...props}>{children}</button>;
}
export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${className}`}>{children}</section>; }
export function Badge({ children, tone = "gray" }: { children: ReactNode; tone?: Tone }) { return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${toneClasses[tone]}`}>{children}</span>; }
export function StatusBadge({ status }: { status: TripStatus }) { const tone: Tone = status === "active" ? "green" : status === "delayed" || status === "gps_stale" ? "amber" : status === "gps_lost" || status === "cancelled" ? "red" : "gray"; return <Badge tone={tone}>{status.replace("_", " ").toUpperCase()}</Badge>; }
export function AlertBanner({ title, message, tone = "amber" }: { title: string; message: string; tone?: Tone }) { return <div role="status" className={`rounded-2xl p-4 ${toneClasses[tone]}`}><strong>{title}</strong><p className="mt-1 text-sm">{message}</p></div>; }
export function DashboardMetricCard({ label, value, helper, tone = "navy" }: { label: string; value: string | number; helper: string; tone?: Tone }) { return <Card><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p><p className="mt-1 text-sm text-slate-500">{helper}</p></div><Badge tone={tone}>Live</Badge></div></Card>; }
export function EmptyState({ title, message }: { title: string; message: string }) { return <Card className="text-center"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm text-slate-500">{message}</p></Card>; }
export function LoadingState({ label = "Loading demo data" }: { label?: string }) { return <div className="rounded-xl bg-slate-100 p-4 text-sm text-slate-600">{label}…</div>; }
export function ErrorState({ message }: { message: string }) { return <AlertBanner tone="red" title="Something needs attention" message={message} />; }
export type Column<T> = { key: string; header: string; render: (row: T) => ReactNode };
export function DataTable<T>({ columns, rows }: { columns: Column<T>[]; rows: T[] }) { return <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b text-slate-500">{columns.map((c) => <th className="px-3 py-3 font-bold" key={c.key}>{c.header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-b last:border-0" key={index}>{columns.map((c) => <td className="px-3 py-3" key={c.key}>{c.render(row)}</td>)}</tr>)}</tbody></table></div>; }
export function Timeline({ items }: { items: { time: string; title: string; detail: string }[] }) { return <ol className="space-y-3">{items.map((item) => <li className="border-l-4 border-yellow-300 pl-4" key={`${item.time}-${item.title}`}><p className="font-semibold text-slate-950">{item.title}</p><p className="text-sm text-slate-500">{item.time} · {item.detail}</p></li>)}</ol>; }
export function NotificationCard({ title, message, meta }: { title: string; message: string; meta: string }) { return <Card><p className="font-bold text-slate-950">{title}</p><p className="mt-1 text-sm text-slate-600">{message}</p><p className="mt-3 text-xs text-slate-400">{meta}</p></Card>; }
export function BusStatusCard({ status, detail }: { status: string; detail: string }) { return <Card className="bg-slate-950 text-white"><p className="text-sm text-yellow-300">Assigned bus status</p><h2 className="mt-2 text-2xl font-black">{status}</h2><p className="mt-2 text-slate-300">{detail}</p></Card>; }
export function DriverActionButton({ label, helper }: { label: string; helper: string }) { return <button className="w-full rounded-2xl bg-slate-900 p-5 text-left text-white shadow-sm"><span className="block text-lg font-black">{label}</span><span className="mt-1 block text-sm text-slate-300">{helper}</span></button>; }
